create table if not exists public.birdle_leaderboad (
  id bigint generated by default as identity primary key,
  player_name text not null,
  score integer not null,
  difficulty text not null,
  best_combo integer not null,
  hits integer not null,
  misses integer not null,
  created_at timestamptz not null default timezone('utc'::text, now()),
  constraint birdle_leaderboad_player_name_check
    check (char_length(trim(player_name)) between 1 and 24),
  constraint birdle_leaderboad_score_check
    check (score between 0 and 5000),
  constraint birdle_leaderboad_difficulty_check
    check (difficulty in ('regular', 'expert')),
  constraint birdle_leaderboad_best_combo_check
    check (best_combo >= 1),
  constraint birdle_leaderboad_hits_check
    check (hits >= 0),
  constraint birdle_leaderboad_misses_check
    check (misses >= 0)
);

create index if not exists birdle_leaderboad_score_created_idx
  on public.birdle_leaderboad (score desc, created_at asc);

alter table public.birdle_leaderboad enable row level security;

grant select, insert on public.birdle_leaderboad to anon;
grant select, insert on public.birdle_leaderboad to authenticated;

drop policy if exists "Birdle leaderboard is readable" on public.birdle_leaderboad;
create policy "Birdle leaderboard is readable"
  on public.birdle_leaderboad
  for select
  to anon, authenticated
  using (true);

drop policy if exists "Birdle leaderboard accepts public inserts" on public.birdle_leaderboad;
create policy "Birdle leaderboard accepts public inserts"
  on public.birdle_leaderboad
  for insert
  to anon, authenticated
  with check (
    char_length(trim(player_name)) between 1 and 24
    and score between 0 and 5000
    and difficulty in ('regular', 'expert')
    and best_combo >= 1
    and hits >= 0
    and misses >= 0
  );